services:
  
  mqtt_broker:
    image: eclipse-mosquitto:2.0.22
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  database:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=supersecretpassword
      - DOCKER_INFLUXDB_INIT_ORG=KPI
      - DOCKER_INFLUXDB_INIT_BUCKET=turbines
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-token

  visualizer:
    image: grafana/grafana:11.1.0 
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  mosquitto_data:
  mosquitto_log:
  influxdb_data:
  grafana_data: