services:
  
  # --- 1. Infrastructure Services ---
  mqtt_broker:
    image: eclipse-mosquitto:2.0.22
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - iot-net

  database:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    networks:
      - iot-net

  # --- 2. Python Application Services ---
  sensor_emulator:
    build:
      context: .
      dockerfile: sensor_emulator/Dockerfile
    depends_on:
      - mqtt_broker
    networks:
      - iot-net
    env_file:
      - .env
    environment:
    - MQTT_QOS=${MQTT_QOS}

  data_collector:
    build:
      context: .
      dockerfile: data_collector/Dockerfile
    depends_on:
      - mqtt_broker
      - database
    networks:
      - iot-net
    env_file:
      - .env
    environment:
    - MQTT_QOS=${MQTT_QOS}
  
  alerter:
    build:
      context: .
      dockerfile: alerter/Dockerfile
    depends_on:
      - mqtt_broker
    networks:
      - iot-net
    env_file:
      - .env
    environment:
    - MQTT_QOS=${MQTT_QOS}
  
  # --- 3. Our Dashboard Service ---
  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./dashboard:/app
    depends_on:
      - database
      - data_collector
    networks:
      - iot-net
    env_file:
      - .env
      
volumes:
  mosquitto_data:
  mosquitto_log:
  influxdb_data:

networks:
  iot-net:
    driver: bridge